name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential autotools-dev autoconf
    
    - name: Configure
      run: |
        autoreconf -fiv
        CFLAGS="-Wall -Wextra -Werror -D_FORTIFY_SOURCE=2 -fstack-protector-strong -O2" \
        LDFLAGS="-Wl,-z,relro -Wl,-z,now" \
        ./configure
    
    - name: Build
      run: make
    
    - name: Run tests
      run: make test
    
    - name: Display test failures
      if: failure()
      run: |
        echo "Test failures detected. Displaying error details:"
        echo "================================================"
        if [ -d test ]; then
          cd test
          for diff_file in *.diff; do
            if [ -f "$diff_file" ]; then
              echo "--- Failure in $diff_file ---"
              cat "$diff_file"
              echo ""
            fi
          done
          if [ -f conserver.log ]; then
            echo "--- Conserver log ---"
            tail -50 conserver.log
          fi
        fi
        echo "================================================"
    
    - name: Upload test artifacts
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: test-results
        path: |
          test/*.diff
          test/conserver.log
        if-no-files-found: ignore
  static-analysis:
    runs-on: ubuntu-latest
    # Run in parallel with tests for faster feedback
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Install static analysis tools
      run: |
        sudo apt-get update
        sudo apt-get install -y cppcheck clang clang-tools build-essential autotools-dev autoconf
    
    - name: Configure project
      run: |
        autoreconf -fiv
        ./configure
    
    - name: Run Clang Static Analyzer
      run: |
        echo "Running Clang Static Analyzer..."
        echo "================================"
        CLANG_VERSION=$(ls /usr/bin/clang-* | grep -E 'clang-[0-9]+$' | sed 's/.*clang-//' | head -1)
        
        scan-build --use-analyzer=/usr/bin/clang-${CLANG_VERSION} --status-bugs \
          -o /tmp/clang-analysis --html-title="Static Analysis Results" \
          --exclude /usr/include \
          make clean && make
        echo "================================"
        echo "Clang Static Analyzer complete"
        if [ -d "/tmp/clang-analysis" ] && find /tmp/clang-analysis -name '*.html' | grep -q .; then
          echo "::error::Static analysis found issues"
          find /tmp/clang-analysis -name "index.html" -exec dirname {} \; | head -1 | xargs -I {} echo "Report directory: {}"
          exit 1
        fi
    
    - name: Run cppcheck
      run: |
        echo "Running cppcheck static analysis..."
        echo "================================"
        cppcheck --enable=all --std=c99 --suppress=missingIncludeSystem --force \
          --error-exitcode=1 \
          conserver/ console/ autologin/ contrib/chat/
        echo "================================"
        echo "Cppcheck analysis complete"

  sanitizer-tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        sanitizer: [address, undefined]
    
    name: Test with ${{ matrix.sanitizer }} sanitizer
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential autotools-dev autoconf
    
    - name: Configure with ${{ matrix.sanitizer }} sanitizer
      run: |
        autoreconf -fiv
        if [ "${{ matrix.sanitizer }}" = "address" ]; then
          export CFLAGS="-fsanitize=address -fno-omit-frame-pointer -g"
          export LDFLAGS="-fsanitize=address"
        elif [ "${{ matrix.sanitizer }}" = "undefined" ]; then
          export CFLAGS="-fsanitize=undefined -fno-omit-frame-pointer -g"
          export LDFLAGS="-fsanitize=undefined"
        fi
        ./configure
    
    - name: Build with sanitizer
      run: make
    
    - name: Run tests with sanitizer
      run: |
        if [ "${{ matrix.sanitizer }}" = "address" ]; then
          export ASAN_OPTIONS=detect_leaks=1:check_initialization_order=1:strict_string_checks=1
        elif [ "${{ matrix.sanitizer }}" = "undefined" ]; then
          export UBSAN_OPTIONS=print_stacktrace=1:halt_on_error=1
        fi
        make test
    
    - name: Upload sanitizer logs
      if: failure()
      uses: actions/upload-artifact@v4
      with:
        name: ${{ matrix.sanitizer }}-sanitizer-results
        path: |
          test/*.diff
          test/conserver.log
        if-no-files-found: ignore
