name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential autotools-dev autoconf
    
    - name: Configure
      run: |
        autoreconf -fiv
        ./configure
    
    - name: Build
      run: make
    
    - name: Run tests
      run: make test
    
    - name: Upload test artifacts
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: test-results
        path: |
          test/*.diff
          test/conserver.log
        if-no-files-found: ignore
  static-analysis:
    runs-on: ubuntu-latest
    needs: test  # Run after the test job completes successfully
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Install static analysis tools
      run: |
        sudo apt-get update
        sudo apt-get install -y cppcheck clang clang-tools build-essential autotools-dev autoconf
    
    - name: Configure project
      run: |
        autoreconf -fiv
        ./configure
    
    - name: Run cppcheck
      run: |
        echo "Running cppcheck static analysis..."
        echo "================================"
        cppcheck --enable=all --std=c99 --suppress=missingIncludeSystem \
          conserver/ console/ autologin/ contrib/chat/ || true
        echo "================================"
        echo "Cppcheck analysis complete"
    
    - name: Run Clang Static Analyzer
      run: |
        echo "Running Clang Static Analyzer..."
        echo "================================"
        scan-build --use-analyzer=clang --status-bugs -o /tmp/clang-analysis \
          make clean && make || true
        echo "================================"
        echo "Clang Static Analyzer complete"
        if [ -d "/tmp/clang-analysis" ] && [ "$(find /tmp/clang-analysis -name '*.html' | wc -l)" -gt 0 ]; then
          echo "Found static analysis issues:"
          find /tmp/clang-analysis -name "*.html" -exec echo "Report: {}" \; -exec cat {} \;
        else
          echo "No static analysis issues found"
        fi
